### ISSUE TITLE
Panic: integer divide by zero in splitHistogram

### ISSUE THREAD

**Issue by Tri125** [bradymadden97/go-quads#4]
I haven't setup my debugger to look at this into detail but what I did is use this [image](https://imgur.com/a/OKL9r) and I specified that I wanted 800 iterations:

``./quads.exe -f rdv68Y7.png -i 800``

```
main.splitHistogram(0xc043cc26c0, 0x1, 0x1, 0x0, 0x0, 0x320, 0xc042438010, 0x4, 0x4)
        E:/Users/Tristan/Documents/Go/src/github.com/bradymadden97/go-quads/quads/quads.go:117 +0x85f
main.iterate(0xc042f887a0, 0xc04200a0e0, 0x320, 0xc042008210, 0xb, 0x0, 0x55ce29, 0x5, 0x404300, 0xc042012298, ...)
```

If 20 iterations are specified, no problem. At 21 it will start to panic.

**Comment by bradymadden97** [comment]
Yep I think I've ran into this before with lower pixel count/ high iteration combinations. I'll check it out tomorrow.

**Comment by bradymadden97** [comment]
Two issues:
1) PNG appears all white - issues reading images with transparent backgrounds
2) Panics when width/ height of subimage == 0 -- **Fixed** to break before
